### ISSUE TITLE
Every element has the same cursor

### ISSUE THREAD

**Issue by SuperStik** [eyedine2/Classic-Steam-Library#16]
The pointer doesn't change to the correct style when hovering over clickable elements.
This is caused by having a global CSS rule only allowing the default cursor.
```css
* {
	cursor: default !important;
}
```
I'm not sure whether this is intentional or not, but I'm filing a report just to be sure.
